% PhD Mathematics and Statistics, Thesis Chapter 1, Alessia Caccamo, University of Exeter, January 2024
function psd_m = generate_spectrum(param_values, freq) % Return the model spectrum
x0 = zeros(1,13); % Initial conditions
x=zeros(1,13); % Vector of state variables
U=0; % Input is set to zero

M = struct(... % DCM model structure
    'dipfit', struct('location', '0', 'symmetry', '0', 'modality', 'LFP', 'type', 'LFP', 'symm', '0', 'Lpos', '0', 'Nm', '1', 'Nc', '1', 'model', 'LFP'),...  
    'IS', 'spm_csd_mtf',...
    'g', 'spm_gx_erp',...
    'f', 'spm_fx_lfp',...
    'x', zeros(1, 13),...
    'n', 13,...
    'pE', struct(),...
    'pC', struct(),...
    'hE', 8,...
    'hC', 1/128,...
    'm', 1,...
    'u', 0,...
    'U', 1.0000,...
    'l', 1,...
    'Hz', freq,...
    'dt', 1);
    
    load("params.mat", 'params');

    % Model parameters
    M.pE = struct(...
    'R', [param_values(1), params(2)],...
    'T', [params(3), params(4)],...
    'G', params(5),...
    'H', [params(6) params(7)  params(8) params(9) params(10)],...
    'A', [params(11), params(12), params(13)],...
    'C', 0,...
    'D', param_values(2),...
    'I', params(15),...
    'Lpos', [0; 0; 0],...
    'L', 1,...
    'l', 1,...
    'J', [0 0 0 0 0 0 0 0 1 0 0 0 0],...
   'a', [params(16); params(17)],...
    'b', [params(18); params(19)],...
    'c', [params(20); params(21)],...
    'd', [params(22); params(23); params(24); params(25)],...
    'f', [params(26); params(27)]);
    P=M.pE;
    P.A = num2cell(P.A); 
    spectrum=spm_csd_mtf(P,M,U); % Use the parameter vector P to generate the spectrum.
    psd_m = real(spectrum{1});
    
return 
    
